export const mockBrokers = [
  {
    id: 'broker-1',
    name: 'Carlos Eduardo Mendes',
    creci: 'CRECI 128.452-F',
    email: 'carlos.mendes@primeimoveis.com.br',
    phone: '(11) 98765-4321',
    whatsapp: '5511987654321',
    photoUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=600&auto=format&fit=crop&q=80',
    bio: 'Especialista em casas em condomínios fechados e imóveis corporativos na Zona Sul e Oeste. Mais de 12 anos de atuação no mercado imobiliário.',
    specialties: ['Casas em Condomínio', 'Alto Padrão', 'Áreas Comerciais'],
    active: true,
    createdAt: new Date(),
  },
  {
    id: 'broker-2',
    name: 'Ana Paula Vasconcelos',
    creci: 'CRECI 194.882-F',
    email: 'ana.paula@primeimoveis.com.br',
    phone: '(11) 99123-8899',
    whatsapp: '5511991238899',
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&auto=format&fit=crop&q=80',
    bio: 'Consultora especialista em coberturas, apartamentos de luxo no Itaim Bibi, Jardins e Moema.',
    specialties: ['Coberturas Duplex', 'Lançamentos', 'Apartamentos Luxo'],
    active: true,
    createdAt: new Date(),
  },
  {
    id: 'broker-3',
    name: 'Roberto Santos Silva',
    creci: 'CRECI 210.339-F',
    email: 'roberto.santos@primeimoveis.com.br',
    phone: '(11) 97455-1122',
    whatsapp: '5511974551122',
    photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=600&auto=format&fit=crop&q=80',
    bio: 'Especializado em terrenos, loteamentos e aluguéis residenciais e comerciais. Foco em negociações ágeis.',
    specialties: ['Terrenos & Lotes', 'Locação Residencial', 'Investimentos'],
    active: true,
    createdAt: new Date(),
  }
];

export const mockProperties = [
  {
    id: 'prop-1',
    code: 'IMV-2001',
    title: 'Casa Neoclássica em Condomínio Alphaville',
    slug: 'casa-neoclassica-em-condominio-alphaville',
    description: 'Espetacular residência neoclássica com fino acabamento em mármore importado, pé direito duplo, automação residencial completa, adega climatizada para 300 garrafas, e paisagismo assinado. Área gourmet integrada com piscina aquecida e sauna a vapor.',
    type: 'venda',
    category: 'casa',
    price: '4850000.00',
    condoFee: '1850.00',
    iptu: '980.00',
    bedrooms: 5,
    suites: 5,
    bathrooms: 7,
    parkingSpaces: 6,
    totalArea: 850,
    builtArea: 620,
    address: 'Alameda dos Ipês, 450 - Condomínio Alphaville 1',
    neighborhood: 'Alphaville',
    city: 'Barueri',
    state: 'SP',
    zipCode: '06470-000',
    latitude: '-23.4981000',
    longitude: '-46.8520000',
    status: 'disponivel',
    featured: true,
    whatsappDirectEnabled: true,
    brokerId: 'broker-1',
    coverImage: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=1200&auto=format&fit=crop&q=80'
    ],
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    virtualTourUrl: 'https://my.matterport.com/show/?m=sample',
    amenities: ['Piscina Aquecida', 'Área Gourmet', 'Portaria 24h', 'Automação', 'Energia Solar', 'Ar Condicionado Central', 'Sauna', 'Adega'],
    viewsCount: 342,
    createdAt: new Date(),
    updatedAt: new Date(),
    broker: null,
  },
  {
    id: 'prop-2',
    code: 'IMV-2002',
    title: 'Cobertura Duplex de Luxo com Vista Panorâmica no Itaim Bibi',
    slug: 'cobertura-duplex-de-luxo-itaim-bibi',
    description: 'Exclusiva cobertura duplex totalmente reformada por renomado arquiteto. Terraço amplo com jacuzzi privativa, espaço gourmet, vista 360 graus para o Parque do Povo. Suíte master com hidromassagem e walk-in closet duplo.',
    type: 'venda',
    category: 'cobertura',
    price: '6900000.00',
    condoFee: '3400.00',
    iptu: '1800.00',
    bedrooms: 4,
    suites: 4,
    bathrooms: 6,
    parkingSpaces: 5,
    totalArea: 480,
    builtArea: 480,
    address: 'Rua Horácio Lafer, 120 - Itaim Bibi',
    neighborhood: 'Itaim Bibi',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '04538-080',
    latitude: '-23.5830000',
    longitude: '-46.6800000',
    status: 'disponivel',
    featured: true,
    whatsappDirectEnabled: true,
    brokerId: 'broker-2',
    coverImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&auto=format&fit=crop&q=80'
    ],
    videoUrl: '',
    virtualTourUrl: '',
    amenities: ['Jacuzzi Privativa', 'Vista Panorâmica', 'Portaria 24h', 'Academia no Prédio', 'Gerador', 'Elevador Privativo', 'Mobiliado'],
    viewsCount: 512,
    createdAt: new Date(),
    updatedAt: new Date(),
    broker: null,
  },
  {
    id: 'prop-3',
    code: 'IMV-2003',
    title: 'Terreno Plano Residencial em Condomínio Fechado Quinta da Baroneza',
    slug: 'terreno-plano-quinta-da-baroneza',
    description: 'Oportunidade ímpar! Terreno espetacular de 1.200m² totalmente plano, de esquina, próximo ao clube e campo de golfe. Projeto arquitetônico aprovado incluso no valor. Segurança máxima 24h e heliponto.',
    type: 'venda',
    category: 'terreno',
    price: '1950000.00',
    condoFee: '2100.00',
    iptu: '450.00',
    bedrooms: 0,
    suites: 0,
    bathrooms: 0,
    parkingSpaces: 0,
    totalArea: 1200,
    builtArea: 0,
    address: 'Rodovia Alkindar Monteiro Junqueira, km 23 - Quinta da Baroneza',
    neighborhood: 'Quinta da Baroneza',
    city: 'Itatiba',
    state: 'SP',
    zipCode: '13250-000',
    latitude: '-23.0010000',
    longitude: '-46.8400000',
    status: 'disponivel',
    featured: true,
    whatsappDirectEnabled: true,
    brokerId: 'broker-3',
    coverImage: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1524813686514-a57563d77965?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&auto=format&fit=crop&q=80'
    ],
    videoUrl: '',
    virtualTourUrl: '',
    amenities: ['Condomínio Fechado', 'Portaria 24h', 'Campo de Golfe', 'Heliponto', 'Clube Completo', 'Quadra de Tênis'],
    viewsCount: 289,
    createdAt: new Date(),
    updatedAt: new Date(),
    broker: null,
  },
  {
    id: 'prop-4',
    code: 'IMV-2004',
    title: 'Apartamento Design Moderno com Varanda Gourmet Pinheiros',
    slug: 'apartamento-design-moderno-pinheiros',
    description: 'Lindo apartamento pronto para morar no coração de Pinheiros. Varanda integrada com fechamento em vidro, churrasqueira, móveis planejados de alta qualidade, ar condicionado inverter em todos os ambientes e 2 vagas demarcadas.',
    type: 'ambos',
    category: 'apartamento',
    price: '1280000.00',
    condoFee: '950.00',
    iptu: '320.00',
    bedrooms: 2,
    suites: 2,
    bathrooms: 3,
    parkingSpaces: 2,
    totalArea: 92,
    builtArea: 92,
    address: 'Rua Fradique Coutinho, 890 - Pinheiros',
    neighborhood: 'Pinheiros',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '05416-001',
    latitude: '-23.5610000',
    longitude: '-46.6900000',
    status: 'disponivel',
    featured: true,
    whatsappDirectEnabled: true,
    brokerId: 'broker-3',
    coverImage: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&auto=format&fit=crop&q=80'
    ],
    videoUrl: '',
    virtualTourUrl: '',
    amenities: ['Varanda Gourmet', 'Piscina na Cobertura', 'Academia', 'Pet Friendly', 'Coworking', 'Portaria Remota 24h'],
    viewsCount: 410,
    createdAt: new Date(),
    updatedAt: new Date(),
    broker: null,
  },
  {
    id: 'prop-5',
    code: 'IMV-2005',
    title: 'Lote Urbano Premium em Condomínio Villa Solaia',
    slug: 'lote-urbano-premium-villa-solaia',
    description: 'Lote privilegiado em rua sem saída, topografia suave com pequeno aclive, proporcionando vista livre e definitiva para a reserva florestal do condomínio. Infraestrutura subterrânea de energia e fibra óptica.',
    type: 'venda',
    category: 'terreno',
    price: '920000.00',
    condoFee: '980.00',
    iptu: '280.00',
    bedrooms: 0,
    suites: 0,
    bathrooms: 0,
    parkingSpaces: 0,
    totalArea: 520,
    builtArea: 0,
    address: 'Av. Solaia, Quadra B - Tamboré',
    neighborhood: 'Tamboré',
    city: 'Barueri',
    state: 'SP',
    zipCode: '06455-000',
    latitude: '-23.4890000',
    longitude: '-46.8390000',
    status: 'disponivel',
    featured: false,
    whatsappDirectEnabled: false,
    brokerId: 'broker-3',
    coverImage: 'https://images.unsplash.com/photo-1524813686514-a57563d77965?w=1200&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1524813686514-a57563d77965?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&auto=format&fit=crop&q=80'
    ],
    videoUrl: '',
    virtualTourUrl: '',
    amenities: ['Portaria 24h', 'Quadra Poliesportiva', 'Playground', 'Fiação Subterrânea'],
    viewsCount: 195,
    createdAt: new Date(),
    updatedAt: new Date(),
    broker: null,
  },
  {
    id: 'prop-6',
    code: 'IMV-2006',
    title: 'Studio Mobiliado e Decorado Vila Olímpia para Locação',
    slug: 'studio-mobiliado-vila-olimpia-locacao',
    description: 'Studio compacto e super funcional, inteiramente planejado com marcenaria sob medida, eletrodomésticos de última geração, Smart TV 55", cama box baú queen, ar condicionado e fechadura eletrônica. Prédio moderno com conceito coliving.',
    type: 'aluguel',
    category: 'apartamento',
    price: '4200.00',
    condoFee: '680.00',
    iptu: '180.00',
    bedrooms: 1,
    suites: 1,
    bathrooms: 1,
    parkingSpaces: 1,
    totalArea: 38,
    builtArea: 38,
    address: 'Rua Funchal, 340 - Vila Olímpia',
    neighborhood: 'Vila Olímpia',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '04551-060',
    latitude: '-23.5950000',
    longitude: '-46.6850000',
    status: 'disponivel',
    featured: false,
    whatsappDirectEnabled: true,
    brokerId: 'broker-3',
    coverImage: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&auto=format&fit=crop&q=80'
    ],
    videoUrl: '',
    virtualTourUrl: '',
    amenities: ['Mobiliado', 'Academia High Tech', 'Lavanderia OMO', 'Rooftop com Barbecue', 'Fechadura Eletrônica', 'Pet Friendly'],
    viewsCount: 620,
    createdAt: new Date(),
    updatedAt: new Date(),
    broker: null,
  },
  {
    id: 'prop-7',
    code: 'IMV-2007',
    title: 'Sobrado Contemporâneo com Piscina Aquecida no Jardins',
    slug: 'sobrado-contemporaneo-jardins',
    description: 'Projeto assinado por escritório premiado, combinando concreto aparente, madeira nobre e grandes aberturas de vidro. Jardim interno com jabuticabeira centenária, solarium com vista para as copas das árvores dos Jardins.',
    type: 'venda',
    category: 'casa',
    price: '5400000.00',
    condoFee: '0.00',
    iptu: '1250.00',
    bedrooms: 4,
    suites: 4,
    bathrooms: 5,
    parkingSpaces: 4,
    totalArea: 450,
    builtArea: 380,
    address: 'Rua Colômbia, 780 - Jardim América',
    neighborhood: 'Jardins',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '01438-000',
    latitude: '-23.5700000',
    longitude: '-46.6720000',
    status: 'disponivel',
    featured: true,
    whatsappDirectEnabled: true,
    brokerId: 'broker-1',
    coverImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&auto=format&fit=crop&q=80'
    ],
    videoUrl: '',
    virtualTourUrl: '',
    amenities: ['Piscina Aquecida', 'Jardim de Inverno', 'Segurança 24h', 'Ar Condicionado Inverter', 'Espaço Gourmet'],
    viewsCount: 480,
    createdAt: new Date(),
    updatedAt: new Date(),
    broker: null,
  }
];

export const mockSettings = {
  id: 'main',
  agencyName: 'Prime Imóveis & Negócios',
  creci: 'CRECI 45.892-J',
  phone: '(11) 3890-4000',
  whatsappDefault: '5511998887777',
  email: 'contato@primeimoveis.com.br',
  address: 'Av. Brigadeiro Faria Lima, 2200 - Itaim Bibi, São Paulo - SP',
  heroTitle: 'Encontre o imóvel ideal para seu estilo de vida',
  heroSubtitle: 'Seu portal completo de Vendas e Aluguéis de Casas, Terrenos, Apartamentos e Coberturas.',
  whatsappTemplateMsg: 'Olá! Tenho interesse no imóvel *{title}* (Cód: *{code}*), no valor de *{price}*. Gostaria de mais informações!',
};

export const mockLeads = [
  {
    id: 'lead-1',
    propertyId: 'prop-1',
    brokerId: 'broker-1',
    clientName: 'Fernando Oliveira',
    clientPhone: '(11) 98822-3344',
    clientEmail: 'fernando.oliveira@email.com',
    type: 'whatsapp_direto',
    message: 'Gostaria de agendar uma visita nesta casa em Alphaville neste sábado.',
    preferredDate: '2026-04-12',
    preferredTime: '10:00',
    status: 'em_atendimento',
    notes: 'Cliente demonstrou alto interesse. Agendado tour virtual inicial.',
    whatsappDirectTriggered: true,
    createdAt: new Date(),
    property: null,
    broker: null,
  },
  {
    id: 'lead-2',
    propertyId: 'prop-2',
    brokerId: 'broker-2',
    clientName: 'Mariana Duarte',
    clientPhone: '(11) 97711-5566',
    clientEmail: 'mariana.duarte@email.com',
    type: 'agendamento_visita',
    message: 'Tenho interesse na cobertura duplex do Itaim. Aceita imóvel de menor valor na negociação?',
    preferredDate: '2026-04-14',
    preferredTime: '15:30',
    status: 'novo',
    notes: '',
    whatsappDirectTriggered: true,
    createdAt: new Date(),
    property: null,
    broker: null,
  }
];
